name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        node-version: 20
        version: 9.14.2

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
